version: 0.0
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "workout-logger-lambda"
        Alias: "dev"
        CurrentVersion: "1"
        TargetVersion: "2"