version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Running JUnit Test cases -- `date`
      - mvn test
  post_build:
    commands:
      - echo Building application -- `date`
      - mvn install
artifacts:
  files:
    - target/workout-logger-0.0.1.jar
    - appspec.yml
    - template.yml
  discard-paths: yes