AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  A simple backend (read/write to DynamoDB) with a RESTful API endpoint using Amazon API Gateway.
Resources:
  microservicehttpendpointpython:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: App.handleRequest
      Runtime: java8
      CodeUri: ./src/main/java
      Description: >-
        A simple backend (read/write to DynamoDB) with a RESTful API endpoint using Amazon API Gateway.
      MemorySize: 128
      Timeout: 10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "users"
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /user
            Method: POST